#spring.datasource.url=${AZURE_DB_URL}
#spring.datasource.username=${AZURE_DB_USERNAME}
#spring.datasource.password=${AZURE_DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#

#
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration