spring.application.name=oenskeskyen
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:mysql://wishlist.mysql.database.azure.com:3306/wishlist
spring.datasource.username=adminLog@Wishlist
spring.datasource.password=Password!


